### ISSUE TITLE
Failed to decrypt a PLAYREADY-encrypted smooth streaming fMP4 with the given content key

### ISSUE THREAD

**Issue by adidaz2011** [axiomatic-systems/Bento4#130]
Here are some sample files encrypted by playready:
http://playready.azurewebsites.net/Home/AdaptiveTests

I tried to use mp4decrypt the following file

http://playready.eastus2.cloudapp.azure.com/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720_230.ismv

with this content key given on the page
09E367028F33436CA5DD60FFE6671E70

but the resultant output was NOT decrypted properly.
Does bento4 support playready encryption/decryption?

**Comment by barbibulle** [comment]
Bento4 does fully support PlayReady encryption and decryption.
The problem here is that 09E36702-8F33-436C-A5DD-60FFE6671E70 shown on the page isn't the content key, but the content key *ID*. The key is obtained by a compliant and secure PlayReady client by getting a license from the license server. The license server typically derives the content key from the content key ID (aka KID) and a 'seed'. Since the seed value isn't provided on the test page, it isn't possible to know what the content key is...

**Comment by adidaz2011** [comment]
Oh, I messed up content key and content key ID. Well, I'm interested in PLAYREADY encryption and decryption. Are there any clear and encrypted test file pairs with a known content key available online?
