### ISSUE TITLE
4k video saying "Video tracks are not aligned"

### ISSUE THREAD

**Issue by zocheyado** [axiomatic-systems/Bento4#156]
I am using FFMPEG to output a video file in many resolutions (360, 480, 720, 1080, 1440 and 2160) and each with a high medium and low bitrate. If I then try and run mp4dash on them it works perfectly. However if the video has a 4k variant it does not work. I can run my command with any number of files seemingly without issue but whenever I add a 4k option it fails. Any idea why this could be? The same command is getting run on ffmpeg with the only variable being bitrate and resolution.

**Comment by barbibulle** [comment]
If you get this error, it means that your encoder has created an output where the key frames in different bitrates are not at the same place in the video. It is important to make sure you configure your encoder to produce the same key frames at all bitrates, otherwise your segments won't be aligned, and you won't be able to create a valid DASH presentation (in order for the decoder to seamlessly switch from one bitrate to another, the segments need to be aligned)

**Comment by zocheyado** [comment]
Gotcha, that makes sense I guess that FFMPEG or any encoder might chose a different keyframe based on the bitrate / resolution. While this has nothing to do with Bento4 do you happen to know the FFMPEG command to set keyframes at a set interval?

**Comment by barbibulle** [comment]
If you look at the mp4-dash-encode.py tool that's included in Bento4, it calls ffmpeg with options that should ensure that key frames are all spaced equally.

**Comment by zocheyado** [comment]
You are correct after a series of test it appears that a combination of ffmpeg commands go this working. -g, -movflags to be specific.
