### ISSUE TITLE
How Bandwidth is calculated and written in Manifest file 

### ISSUE THREAD

**Issue by Natarajan92** [axiomatic-systems/Bento4#158]
Hi, 

We have created ABR Mpeg-Dash stream in four profiles (650Kbps, 1200Kbps, 2400Kbps and 4800Kbps). After packaging the manifest file video adaptation set looks like below and sample manifest file is attached

> "AdaptationSet

 maxHeight="720" maxWidth="1280" mimeType="video/mp4" minHeight="288" minWidth="512" segmentAlignment="true" startWithSAP="1"><SegmentTemplate duration="4004" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4s" startNumber="1" timescale="1000"/><Representation bandwidth="531064" codecs="avc1.4D4015" frameRate="24000/1001" height="288" id="video/1" scanType="progressive" width="512"/><Representation bandwidth="1173760" codecs="avc1.4D401F" frameRate="24000/1001" height="576" id="video/2" scanType="progressive" width="1024"/><Representation bandwidth="2594265" codecs="avc1.4D401F" frameRate="24000/1001" height="720" id="video/3" scanType="progressive" width="1280"/><Representation bandwidth="5425530" codecs="avc1.4D401F" frameRate="24000/1001" height="720" id="video/4" scanType="progressive" 

> width="1280"/></AdaptationSet>"

In Manifest file the Representation bandwidth value is higher than what we mention while encoding. The Mediainfo and FFmpeg gives the bitrate value as 4489kb/s after encoding. 

So, How the bandwidth of the encoded file is calculated and being represented in manifest file for playback ?

Due to higher bandwidth value mentioned in manifest file, The client player will get playback problem over internet ? 

For testing purpose we have created manifest file with single bit-rate representations too which will be played by restricting the bandwidth as high 5000kbps. 

When it comes to 4800kbps single profile playback test with bandwidth restriction of 5000kbps, the manifest file has representation higher than 5000kbps. Will it cause playback problem ?  

[Support_Issue_Mpd.txt](https://github.com/axiomatic-systems/Bento4/files/1107711/Support_Issue_Mpd.txt)

**Comment by barbibulle** [comment]
The reason you are seeing a different value for the bandwidth in the MPD and from ffmpeg/mediainfo is because the MPD value is computed in a different way, in order to comply with the specification. The bandwidth reported by ffmpeg or mediainfo is the *average* bandwidth for the stream (number of bytes divided by duration), whereas for the MPD the calculation is done by segment, and also based on the buffer model, that takes the minBufferTime into account. To be more specific, the value is an indication to the player that if it starts playing after having buffered 'minBufferTime', and if the network bandwidth is exactly the value in the MPD, then the buffer will never completely empty. So if your encoder creates segments for which the average bitrate for the segment is higher, or if within a segment you have a higher bitrate at some point of the the segment than other points, you will see the MPD bandwidth value be somewhat different from the stream's average bandwidth.

**Comment by qchroman** [comment]
I'm sorry, I came across this value within my work which involves content download and I was also wondering about the calculation as the size of the chunk you download can't be really calculated based on the stream length and the bandwidth because the bandwidth is higher. You are saying 

> in order to comply with the specification

What do you mean by that if you don't mind me asking? Do you happen to have a link to the specification?
