### ISSUE TITLE
Bento packaged hls not playing on macOS Safari 

### ISSUE THREAD

**Issue by AlphaSolutions7** [axiomatic-systems/Bento4#163]
Hello,
Is there any known issues with bento packaged hls and Safari on MacOS?  We tried different players and different packaging tools, with the same source video, all worked fine but the one we produced with bento failed to play.  for example hls.js, and apple native player with Shaka produced hls worked fine.

here is the command we've been using; 
>mp4-hls.py --hls-version=4  --segment-duration={{segment_length}} --debug --force --output-dir="{{output_folder}}" --master-playlist-name={{asset_id}}.m3u8 {{input_file_group}}

**Comment by barbibulle** [comment]
I'm not able to reproduce the problem. HLS streams generated with this syntax work perfectly well on my system (macOS Sierra, with Safari).
Can you share the input and output files you have used for your test so that I can replicate this on my end?

**Comment by AlphaSolutions7** [comment]
here is a link to input and output files 
https://www.dropbox.com/sh/bf9073uypu50l3n/AAAuDs1pGbKEH7UHrBqYF7SDa?dl=0

**Comment by barbibulle** [comment]
The 'out' HLS files work for me on Safari, and I can also re-package the files from the 'in' folder and that works too. 
But I think I might know what the issue is. It looks like you've packaged those files on a Windows machine, and there's an issue with the script adding extra newline characters to text file on Windows (doesn't bother the HLS player on my version of macOS, but it may be an issue for older versions). I will push an update of the tool that doesn't have this Windows issue, I hope it will solve your problem (could you try generating the HLS files on a macOS or Linux machine to see if that's the issue you're having?)

**Comment by AlphaSolutions7** [comment]
@barbibulle  thank you for the linefeed tip, I manually updated the playlist and tested it, it worked. I will keep an eye on the tools update.
