### ISSUE TITLE
mp4fragment: inconsistent fragment duration

### ISSUE THREAD

**Issue by jviney** [axiomatic-systems/Bento4#177]
Hi,

Thanks for the great work with this project.

I am using it with an input that has keyframes every 2.5 seconds.

When running mp4fragment using a `--fragment-duration 6000`, the fragment times alternate between 5 and 7.5 seconds. It would seem better to stick to one rather than alternating.

```
➜  fragtest git:(master) ✗ mp4fragment --fragment-duration 6000 --verbosity 3 30fps.mp4 30fps.fmp4
fragment: track ID 1
 150 samples
 constant sample duration: yes
fragment: track ID 1
 225 samples
 constant sample duration: yes
fragment: track ID 1
 150 samples
 constant sample duration: yes
fragment: track ID 1
 225 samples
 constant sample duration: yes
fragment: track ID 1
 150 samples
 constant sample duration: yes
fragment: track ID 1
 150 samples
 constant sample duration: yes
fragment: track ID 1
 225 samples
 constant sample duration: yes
fragment: track ID 1
 150 samples
 constant sample duration: yes
fragment: track ID 1
 225 samples
 constant sample duration: yes
fragment: track ID 1
 150 samples
 constant sample duration: yes
fragment: track ID 1
 2 samples
 constant sample duration: yes
➜  fragtest git:(master) ✗ 
```

Using the same mp4 with mp42hls produces segments with a consistent 7.5 seconds.

Regards.

**Comment by barbibulle** [comment]
To avoid drifts that can happen when the encoding is "almost" aligned, mp4fragment tries to pick the closest fragment boundary to the regular interval that's requested. So in your case, it will pick the closest key frames to marks at 0,6,12, etc..
An important point here is that mp4fragment will always start a fragment with a key frame, and key frame locations can't be changed after you have encoded the content.
Since you're encoding with a key frame interval of 2.5 seconds, you should be passing to mp4fragment a duration that's a multiple of that. If you use --fragment-duration 5000, you'll get nice equal fragments of 5 seconds each.

**Comment by jviney** [comment]
Thanks, that makes sense. Yes I adjusted the fragment duration as you suggest. Is the behaviour of mp42hls vs mp4fragment intentional?

**Comment by barbibulle** [comment]
In theory, mp42hls should be enhanced to work like mp4fragment, but we haven't had time to do that work yet.
