### ISSUE TITLE
Optional params for mp4mux don't work

### ISSUE THREAD

**Issue by sasmaster** [axiomatic-systems/Bento4#212]
Hi Again,It is not clear how to pass optional params like frame_rate into the app.It also looks like the initial params parsing doesn't take into account optional params at all.

```
  while (char* arg = *++argv) {
        if (!strcmp(arg, "--verbose")) {
            Options.verbose = true;
        } else if (!strcmp(arg, "--track")) {
            input_names.Append(*++argv);
        } else if (output_filename == NULL) {
            output_filename = arg;
        } else {
            fprintf(stderr, "ERROR: unexpected argument '%s'\n", arg);
            return 1;
        }
    }
```
This doc example:

>  usage: mp4mux [options] --track [<type>:]<input>[#<params] [--track [<type>:]<input>[#<params] ...] <output>

Is very confusing. I was trying all kind of combinations but it always throw 👍 

> ERROR: unexpected argument 'frame_rate=60.0'

My command line:  --verbose --track  h264:test.h264 #params  frame_rate=60.0  --track  aac:sample1.aac  test.mp4

**Comment by barbibulle** [comment]
The issue here is that you have a space character between your input name and the params, and also in the #<params> part, you should put your parameters, not the word 'params'.
Example:
mp4mux --track h264:test.h264#frame_rate=60.0 --track aac:sample1.aac test.mp4

(since your input files have expected file extensions, you can even ommit the '<type>:' prefix, so you could use:
mp4mux --track test.h264#frame_rate=60.0 --track sample1.aac test.mp4
