### ISSUE TITLE
Rotating AES-128 Keys

### ISSUE THREAD

**Issue by TheDeadCode** [axiomatic-systems/Bento4#229]
Does Bento4 implement that part of the specification?

**Comment by barbibulle** [comment]
It is partially supported, in the sense that the library, when used from the API, will allow you to support that. However, the command-line tools that are built on top of the API don't currently offer options to rotate the keys, because they are typically used with stored files, not for live content. Key rotation isn't very useful for limited-duration content, like a single video asset, they are more typically used with live/linear streaming content.
Do you have a specific use case in mind?

**Comment by TheDeadCode** [comment]
Right now we have 4 variants of a single file, and ideally we’d like to use one or more keys so people have to refresh their session via Ajax to keep being able to download the key files. This would allow us to keep a tighter control on bots who simply download and decrypt the content, by forcing a session resumption

**Comment by barbibulle** [comment]
I see. But that might not give you much protection: how would you prevent a bot from downloading all the keys at once? And if you did require some time lapse between key requests, how would you allow a normal client player from doing random access to move around in the movie or resume playing from where they left off?

**Comment by TheDeadCode** [comment]
Hey! Sorry -- I don't think I explained myself well (I'm still new to this whole HLS thing). What I meant is keys for different variants. We have user tiers and lower tier only gets access to the 480p rendition while other tiers get 720p+ rendition access. That's what I meant; Sorry!

**Comment by barbibulle** [comment]
Ah, that's a different use case. Makes sense. Using different keys for different variants is a feature we're planning on adding to the next release.

**Comment by TheDeadCode** [comment]
Hi there! I simply wanted to know if there was any follow up on this? We're soon 1 year later and I was curious if this was something that could be done in the next iteration

**Comment by TheDeadCode** [comment]
Hello! Is this next release... released? :)
