### ISSUE TITLE
can't create dash manifest for audio only fragmented mp4

### ISSUE THREAD

**Issue by nickdesaulniers** [axiomatic-systems/Bento4#3]
I have a fragmented mp4 file, but I can't create the dash manifest:

```
➜  mse  ~/Downloads/Bento4-SDK-1-4-2-589.universal-apple-macosx/bin/Release/mp4fragment --fragment-duration 30000 snowblind.mp4 snowblind-frag.mp4
➜  mse  ~/Downloads/Bento4-SDK-1-4-2-589.universal-apple-macosx/utils/mp4-dash.py --profiles=on-demand --use-segment-list snowblind-frag.mp4
Parsing media file 1: snowblind-frag.mp4
Extracting track 1 from snowblind-frag.mp4
no video track, cannot autodetect fragment duration
unable to detect fragment duration, using default
Parsing media file 1: tmpWeIW74 = Extracted[track 1 from snowblind-frag.mp4]
Processing and Copying media file tmpWeIW74 = Extracted[track 1 from snowblind-frag.mp4]
```

https://github.com/axiomatic-systems/Bento4/blob/865ae71572fe5accec10b79f41221f041ea7da0a/Source/C%2B%2B/Apps/Mp4Fragment/Mp4Fragment.cpp#L1026-L1033

Is it possible to get the fragment duration from audio?  Or am I doing something wrong?

**Comment by barbibulle** [comment]
That’s a mistake of the fragmenter. With the on-demand profile, the mp4-dash packager needs to (re)compute the fragment index, so it internally invokes mp4fragment (with the ‘—index’ option). The fragmenter incorrectly complains about not being able to auto-detect the fragment duration. 
For non-fragmented files, audio tracks don’t have a “natural” fragment duration. With video tracks, the fragmenter looks for a regular-interval pattern of I frames in the video, and uses that as the fragment duration if the encoder has encoded the video that way. With audio, there’s no equivalent to I frames, as all frames are valid random access points. If you invoke the fragmenter without an explicit requested fragment duration, it will try to auto-detect a duration. If it can’t (either because the video doesn’t have a regular I frame pattern or because there’s no video), it will use the default setting of 2 seconds. 
What I need to do here is add a feature to mp4fragment so that when it is being asked to recompute the index for an audio-only file that’s already fragmented, it will keep the original fragment layout the same (unfortunately with audio, you won’t end up with segments of exactly equal duration when you fragment a file with an integral number of seconds per fragment, because there are non-integral numbers of audio frames in a second). 
Until I produce this fix, things should still work, albeit with the warning you are seeing, which means that the fragment duration in the re-indexed file will be the default (2 seconds) instead of what you had originally selected (30 seconds).

By the way, the --use-segment-list option isn’t valid with the on-demand profile. I’m surprised you’re not seeing an error.

-- Gilles


On April 7, 2015 at 12:11:43 PM, Nick Desaulniers (notifications@github.com) wrote:

I have a fragmented mp4 file, but I can't create the dash manifest:

➜  mse  ~/Downloads/Bento4-SDK-1-4-2-589.universal-apple-macosx/bin/Release/mp4fragment --fragment-duration 30000 snowblind.mp4 snowblind-frag.mp4
➜  mse  ~/Downloads/Bento4-SDK-1-4-2-589.universal-apple-macosx/utils/mp4-dash.py --profiles=on-demand --use-segment-list snowblind-frag.mp4
Parsing media file 1: snowblind-frag.mp4
Extracting track 1 from snowblind-frag.mp4
no video track, cannot autodetect fragment duration
unable to detect fragment duration, using default
Parsing media file 1: tmpWeIW74 = Extracted[track 1 from snowblind-frag.mp4]
Processing and Copying media file tmpWeIW74 = Extracted[track 1 from snowblind-frag.mp4]

https://github.com/axiomatic-systems/Bento4/blob/865ae71572fe5accec10b79f41221f041ea7da0a/Source/C%2B%2B/Apps/Mp4Fragment/Mp4Fragment.cpp#L1026-L1033

Is it possible to get the fragment duration from audio? Or am I doing something wrong?

**Comment by barbibulle** [comment]
This is fixed now
