### ISSUE TITLE
Smooth Streaming ismv encryption

### ISSUE THREAD

**Issue by armin884** [axiomatic-systems/Bento4#402]
I have an smoothstreaming fragmented .ism/Manifest with ``` <ProtectionHeader SystemID="9a04f079-9840-4286-ab92-e65be0885f95"> ``` . My problem is the downloaded ismv video is missing any encryption data, no PSSH, no KID, no WRMHEADER inside the file when using mp4dump. How can i add that data to file?

**Comment by barbibulle** [comment]
Is the original manifest and stream something that you created, or just something you're downloading from somewhere. If you created the stream, I would suggest adding this metadata at creation time rather than trying to add it later. If you didn't create the file, I'm afraid that adding this type of metadata later isn't going to be useful, because if the media is encrypted and you don't have the encryption keys, it won't be of much use.
