### ISSUE TITLE
Converting to hex to value similar to key.bin is not matching in C#

### ISSUE THREAD

**Issue by NvVijayakumara** [axiomatic-systems/Bento4#427]
Hi,

I'm using below command, it's able to generate required files for hls stream and also generates 'key.bin'
`mp4hls "D:\file.mp4" --output-single-file --encryption-mode="AES-128" --encryption-key="22b44eee1236cf62f3b655b17fb31f33" --output-encryption-key`

When I open 'key.bin', it's content is 
`"´Nî6Ïbó¶U±³3`

As I'm a c# developer, tried using below code to get value similar to key.bin
// c# code
`byte[] data = new byte[] { 0x22, 0xb4, 0x4e, 0xee, 0x12, 0x36, 0xcf, 0x62, 0xf3, 0xb6, 0x55, 0xb1, 0x7f, 0xb3, 0x1f, 0x33 };`
`string ascii = Encoding.ASCII.GetString(data);`
`Console.WriteLine(ascii);`
// but result is as below, its not matching to key.bin
`"?N?6?b??U??3`

Im just stucked here, can someone help me.

Thanks

**Comment by barbibulle** [comment]
I'm not a C# expert, but it seems here that going through an ASCII encoding is a problem. The bytes are not all in the ASCII range.
From the C# doc, I can see that it says:
**ASCIIEncoding does not provide error detection. Any byte greater than hexadecimal 0x7F is decoded as the Unicode question mark ("?").**
Also, looking at the contents of `key.bin` as text is misleading, for the same reason: there are non-printable bytes in that file. I would recommend dumping the file as hexadecimal to view its contents.

**Comment by vladimir-kazakov** [comment]
I'm not sure what exactly is needed, but it seems that the goal is to convert a byte array to a hex string, which should be equal to the one provided in the `--encryption-key` option. If this is so, then the correct way of doing it is:

```csharp
var data = new byte[] { 0x22, 0xb4, 0x4e, 0xee, 0x12, 0x36, 0xcf, 0x62, 0xf3, 0xb6, 0x55, 0xb1, 0x7f, 0xb3, 0x1f, 0x33 };

var dataAsHex = BitConverter.ToString(data).Replace("-", "").ToLower();

Console.WriteLine(dataAsHex);
```

> but result is as below, its not matching to key.bin

This seems like another question, and the goal is to compare the contents of the `key.bin` file with the contents of the `data` byte array. Since `key.bin` is a binary file that contains data that does not represent text, it doesn't make any sense to read or open it as text (ASCII, UTF-8, or whatever else). You need to compare binary data. It may look like:

```csharp
var dataInKeyBin = File.ReadAllBytes(pathToKeyBin);

var data = new byte[] { 0x22, 0xb4, 0x4e, 0xee, 0x12, 0x36, 0xcf, 0x62, 0xf3, 0xb6, 0x55, 0xb1, 0x7f, 0xb3, 0x1f, 0x33 };

bool areEqual = dataInKeyBin.SequenceEqual(data);
```

The `SequenceEqual` is defined in the `System.Linq` namespace.

P.S. Of course, there is also an option to convert the binary contents of `key.bin` and `data` to hex strings, and then compare these strings. Same result, different approach.

**Comment by NvVijayakumara** [comment]
Hi.. thanks @vladimir-kazakov .. 
I checked your code, its working, I've another question..

I'm generating and storing hex key (eg. "22b44eee1236cf62f3b655b17fb31f33") in server database.

When player requests for hls video (.m3u8), it has to obtain key by making request to 'getkey' web api by passing certain parameters such as userid, password and video_id.
As of now I've done this api, in response I'm sending hex key string (eg. "22b44eee1236cf62f3b655b17fb31f33").

I'm sure player can't play video using this hex key string, instead we need to supply right key which is similar to content in 'key.bin' file.
 
Is there any way I can convert hex key string to the format which is similar to the one inside key.bin?

Thanks

**Comment by vladimir-kazakov** [comment]
`key.bin` is a byte array (16 bytes), so you need to convert the hex string into a byte array. There are many ways to do it, some may be more efficient than others, but it may look like:

```cs
var keyAsHex = "22b44eee1236cf62f3b655b17fb31f33";

var keyAsByteArray = Enumerable
    .Range(0, keyAsHex.Length / 2)
    .Select(x => Convert.ToByte(keyAsHex.Substring(x * 2, 2), 16))
    .ToArray();
```

P.S. Alternatively, the `getkey` Web API could return binary data (an HTTP response with the Content-Type `application/octet-stream`), so that there is no need to convert anything on the player side.

**Comment by NvVijayakumara** [comment]
Thanks you @vladimir-kazakov
