### ISSUE TITLE
Mp4Info - fails to parse DASH segment produced by mp4-dash.py

### ISSUE THREAD

**Issue by karlg-arris** [axiomatic-systems/Bento4#456]
Hi,

I have content produced by Bento4/mp4-dash.py and I can no longer analyse individual segments using the mp4Info utility.

version (installed on macOS 10.15 via Homebrew)
packager % mp4info
MP4 File Info - Version 1.3.4
(Bento4 Version 1.5.1.0)
(c) 2002-2017 Axiomatic Systems, LLC

Link to segment :https://www.dropbox.com/s/h6p0l0ccdxm0dzc/video_seg1.m4s?dl=0

Error:
No movie found in the file

**Comment by karlg-arris** [comment]
@barbibulle interested to know if this is a real issue or not?

**Comment by barbibulle** [comment]
Individual segments don't contain the shared metadata (codec info, etc.) common to all segments, as that is stored in the "init segment", in what's called the 'movie' part of the file. `mp4info` reads and displays that metadata, so if you pass it just a media segment, it will print out this error, since there's indeed no 'movie' part in the segment.
What type of info do you want to get from the segment? If you want to look at the segment structure, the `mp4dump` utility will show you that. If you want to see the high level track/codec info, use `mp4info` on the "init segment" (often named "init.mp4" if you are looking at the output of the `mp4dash` tool)

**Comment by karlg-arris** [comment]
@barbibulle thanks for the clarification.  using mp4dump works as you describe.
