### ISSUE TITLE
Video track alignment and Audio Issue for vp9 videos

### ISSUE THREAD

**Issue by soniurvi2610** [axiomatic-systems/Bento4#474]
Hi,

We're trying to do dash packaging with multi-bitrate video encoding with vp9 and vorbis/libopus codecs. 

**1. When encoding with one pass**
When encoding videos with ffmpeg one pass and doing it's packaging, generated segments doesn't play audio even though audio tracks are present.
```
cvlc https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_opus_singlepass/dash/manifest.mpd

Error log : 
[00007f356c655a40] vorbis decoder error: this bitstream does not contain Vorbis audio data
```

**2. When encoding video with two pass** 
Once the  transcoding is done with **2 pass**, variants are generated and after fragmentation of these variants we're getting below mentioned error while packaging : 

```
ERROR: video tracks are not aligned ("File 2#1" differs from File 1#1)
```
**A. Video Encoding with Ffmpeg 2pass  :: 360p** 
```
ffmpeg -loglevel debug -hwaccel cuda -i 156MB_3.50min.mp4 -hide_banner -s 640x360 -c:v libvpx-vp9 -b:v 1.2M -maxrate 2.4M -bufsize 2.4M -tile-columns 0 -g 250 -pix_fmt yuv420p -color_primaries bt709 -colorspace bt709 -color_range tv -quality good -ar 48000 -c:a libopus -b:a 192k -ac:a 2 -f mp4 -strict -2  -pass 1 -speed 4 -y -passlogfile 156MB_vp9test_360p_opus.mp4 /dev/null && ffmpeg -loglevel debug -hwaccel cuda -i 156MB_3.50min.mp4 -hide_banner -s 640x360 -c:v libvpx-vp9 -b:v 1.2M -maxrate 2.4M -bufsize 2.4M -tile-columns 0 -g 250 -pix_fmt yuv420p -color_primaries bt709 -colorspace bt709 -color_range tv -quality good -ar 48000 -c:a libopus -b:a 192k -ac:a 2 -f mp4 -strict -2  -pass 2 -speed 2 -y -passlogfile 156MB_vp9test_360p_opus.mp4 '156MB_vp9test_360p_opus.mp4'
```
**B. Video Encoding with Ffmpeg 2pass  :: 480p** 
```
ffmpeg -hwaccel cuda -i 156MB_3.50min.mp4 -hide_banner -s 854x480 -c:v libvpx-vp9 -b:v 2M -maxrate 3.8M -bufsize 3.8M -tile-columns 0 -g 250 -pix_fmt yuv420p -color_primaries bt709 -colorspace bt709 -color_range tv -quality good -ar 48000 -c:a libopus -b:a 192k -ac:a 2 -f mp4 -strict -2  -pass 1 -speed 4 -y -passlogfile 156MB_vp9test_480p_opus.mp4 /dev/null && ffmpeg -hwaccel cuda -i 156MB_3.50min.mp4 -hide_banner -s 854x480 -c:v libvpx-vp9 -b:v 2M -maxrate 3.8M -bufsize 3.8M -tile-columns 0 -g 250 -pix_fmt yuv420p -color_primaries bt709 -colorspace bt709 -color_range tv -quality good -ar 48000 -c:a libopus -b:a 192k -ac:a 2 -f mp4 -strict -2  -pass 2 -speed 2 -y -passlogfile 156MB_vp9test_480p_opus.mp4 '156MB_vp9test_480p_opus.mp4'
```
**C. Fragmentation :: mp4fragment**
```
/opt/bento4/bin/mp4fragment --fragment-duration 10000 --debug 156MB_vp9test_360p_opus.mp4 156MB_vp9test_360p_opus_frag.mp4
/opt/bento4/bin/mp4fragment --fragment-duration 10000 --debug 156MB_vp9test_480p_opus.mp4 156MB_vp9test_480p_opus_frag.mp4
```
**D. Segmentation :: mp4dash** 
```
/opt/bento4/bin/mp4dash -v -d -f -o 156MB_vp9test_opus/dash --mpd-name=manifest.mpd --profiles=live --init-segment=test_init.mp4 --min-buffer-time=1.5 --use-segment-template-number-padding --use-segment-timeline 156MB_vp9test_360p_opus_frag.mp4 156MB_vp9test_480p_opus_frag.mp4
```

The videos can be downloaded from below location :
1. Source file : https://public.jetstream.video/stage/vp9test_new/156MB_VorbisTest/156MB_3.50min.mp4
2. 360p file with 2 pass : 
https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_360p_opus.mp4
3. 480p file with 2 pass : 
https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_480p_opus.mp4
4. 360p file with single pass : 
https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_360p_opus_singlepass.mp4
5. 480p file with single pass : 
https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_480p_opus_singlepass.mp4
6. Dash Streaming url from one pass : 
https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_opus_singlepass/dash/manifest.mpd

**Comment by haridarshan** [comment]
@barbibulle 
Hi,
Any update on this issue

**Comment by barbibulle** [comment]
There are a couple issues I can see here:
1/ the single-pass files are correctly encoded with a fixed-size GOP (Group Of Pictures) of 250 frames (you can see this when you use `mp4fragment` with those files, it will print out that it detected a constant I-frame interval of 250 frames), but the two-pass files are not, they have I-frames located at non-constant intervals. If you use `mp4info --show-samples` you can see the I-frames, they have an `[S]` suffix. With the 360p two-pass file, you can see I-frames at frame 1,251,398,454, etc, which isn't a constant interval).
If you want a multi-rate stream, you need to have your I-frames aligned in different bitrates, hence the need for a constant-interval encoding

2/ For the audio, the problem seems to be that your HTTP server is refusing access to the audio segments. Access to the MPD works, but try an audio segment, and you'll see you get back an 403 (Denied) error. Ex: `curl -v https://public.jetstream.video/stage/vp9test_new/156MB_vp9test_opus_singlepass/dash/audio/und/Opus/Seg-1.m4s > opus-seg-1.m4s`.
