### ISSUE TITLE
bento4 dont work for me

### ISSUE THREAD

**Issue by Ivoyko** [axiomatic-systems/Bento4#486]
i have a video. I used mp4info to see the kid, then i used mp4decrypt with 1:kid video.mp4 video2.mp4. Then stuff finish but new video dont work fine, its just a bunch of random colours without sense.
What i ate to this tool works?

**Comment by barbibulle** [comment]
In order to decrypt a video, you will need not just the KID (Key Identifier), which is specified in the file header, but also the actual decryption key, which is obviously not in the file itself, but that is normally delivered to a secure player using a DRM system. This means that unless you have some way to access the key from the person/system who encrypted the video, you will most likely not have that key to decrypt the audio and video tracks in the file.

**Comment by Ivoyko** [comment]
oh i read some dudes that says u just can with that key, somedudes that u cant... i was confused but thanks.

**Comment by barbibulle** [comment]
```
usage: mp4decrypt [options] <input> <output>
Options are:
  --show-progress : show progress details
  --key <id>:<k>
      <id> is either a track ID in decimal or a 128-bit KID in hex,
      <k> is a 128-bit key in hex
      (several --key options can be used, one for each track or KID)
      note: for dcf files, use 1 as the track index
      note: for Marlin IPMP/ACGK, use 0 as the track ID
      note: KIDs are only applicable to some encryption methods like MPEG-CENC
  --fragments-info <filename>
      Decrypt the fragments read from <input>, with track info read
      from <filename>.
```
