### ISSUE TITLE
Error 8004B8D2 when playing back a CENC-encrypted file

### ISSUE THREAD

**Issue by mc0re** [axiomatic-systems/Bento4#520]
According to an issue in Shaka Player ( https://github.com/google/shaka-player/issues/1813 ), this error occurs when 16-byte IV is used. I use this command to encrypt the file:
```
            var start = new ProcessStartInfo(
                @"mp4encrypt.exe",
                "--method MPEG-CENC " +
                $"--property 1:KID:{keyId} " +
                $"--key 1:{keyValue}:random " +
                $"--key 2:{keyValue}:random " +
                $"--pssh \"{systemId}:{psshFile}\" \"{inputFile}\" \"{outFile}\"")
```

According to the documentation, `MPEG-CENC` expects 8-byte IV, so I expect it generates an 8-byte one as well. For testing, I supplied an explicitly generated IV, the result is the same.

The result is that the file can be played back on my machine, but fails on another machine with error 8004B8D2. The playback is performed by a UWP app.

Have you seen this before? Is there something the other machine is missing in terms of installation? Or is it because I have the development environment, which the other machine does not?

**Comment by swenkeratmicrosoft** [comment]
There are three things that impact whether 16 byte IVs are supported for CENC content.

1. Whether the OS version supports it.
2. Whether you are using Hardware vs Software DRM (e.g. com.microsoft.playready.recommendation.3000 versus com.microsoft.playready.recommendation.2000), as the OS version is different between them.
3. When using Hardware DRM, whether the underlying hardware supports it.

I will assume, for the moment, that you are running the May 2019 Update version (or higher) of Windows 10 on both machines.

In that case, it is highly likely that the failing machine is using Hardware DRM and has older hardware (or firmware) than the passing machine.

The correct behavior is to query whether 16 byte IVs are supported before attempting playback as described in my comment earlier today (2020/06/02) on issue 1813 (which you linked).

Hope that helps,

-Sam Wenker (MSFT)

**Comment by mc0re** [comment]
What can I do if the target machine does not support 16-bit IVs?

**Comment by swenkeratmicrosoft** [comment]
If possible, the best thing to do is fallback to software DRM, re-query support, and playback using software DRM if supported there.  Note that you or the user may need to select a lower resolution version for playback - that entirely depends on the content provider and the website design.

If it's not supported in SWDRM either, you can tell the user that they need to install updates on their machine in order to playback the content and maybe give them a pointer to windows settings/updates - I'm not a UX expert :).  I can tell you that SWDRM always supports 16 byte IVs starting with the Windows 10 May 2019 Update (or higher), so SWDRM will definitely work if they're up to date.

If it's not possible to fallback to SWDRM for some reason (e.g. the content is only available in ultra HD and the content provider insists on HWDRM for that content), then...tell the user that their hardware doesn't support the content?  Maybe tell them to buy a new graphics card?  On a laptop, they might have to buy a newer laptop depending on how upgradable it is?  *shrug*  Basically, if the hardware doesn't support it, the hardware doesn't support it - it's not like the website can upgrade their hardware for them.  :D

Hope that helps,

-Sam Wenker (MSFT)

**Comment by mc0re** [comment]
Fair enough, if it's hardware problem, it can't be updated. But can I enforce `mp4encrypt` to use 8-byte IV? Or may be you see some other potential problem with the call?

**Comment by barbibulle** [comment]
Yes, you can instruct `mp4encrypt` to use 8-byte IVs for CENC.
In fact, when you use the `--playready` option of the `mp4dash` tool, it does that automatically for you, because of this exact problem.
If you just want 8-byte IVs, you can use the `--global-option mpeg-cenc.iv-size-8:true` when invoking `mp4encrypt`. 
Alternatively, you can use `--global-option mpeg-cenc.piff-compatible:true`, which also will use 8-byte IVs, in addition to other things that relate to making the output compatible with the PIFF format (a predecessor of the standardized MPEG CENC format), like including an `senc` box.

When you use `mp4dash` with the `--playready` option, `--global-option mpeg-cenc.piff-compatible:true` will be used when invoking `mp4encrypt` internally (you can verify that by running `mp4encrypt` with the `-d` option, which shows you the sub-commands that are run.

**Comment by mc0re** [comment]
Now that's an answer I like to hear :-) Thanks!
