### ISSUE TITLE
Saving new stream of MP4 audio file loses the existing chapter markers information.

### ISSUE THREAD

**Issue by gmacciocca** [axiomatic-systems/Bento4#529]
Hello,
I am opening an AP4_FileByteStream from a *.m4a file, which contains chapter markers.
I then open a AP4_File using the above stream. 
I then save the size of the moov atom *(GetMovie() -> GetMoovAtom() -> GetSize())
All is good, no problem here.

I then proceed to save the opened stream to a new file with AP4_FileCopier::Write
This is the method to save to the new file

```
bool MP4FileWrapper::saveTo(const char* szOutputFileName) {
	bool success = false;
	assert(this->isOpen() && szOutputFileName);
	if (this->isOpen() && szOutputFileName) {
		// create the output stream
		AP4_ByteStream* pOutputStream = NULL;
		AP4_Result result = AP4_FileByteStream::Create(szOutputFileName, AP4_FileByteStream::STREAM_MODE_WRITE, pOutputStream);
		assert(AP4_SUCCEEDED(result));
		success = AP4_SUCCEEDED(result);
		if (success && pOutputStream) {
			// adjust the chunk offsets if the moov is before the mdat
			if (this->m_moov && this->m_pAP4_File->IsMoovBeforeMdat()) {
				AP4_LargeSize new_moov_size = this->m_moov->GetSize();
				AP4_SI64 size_diff = new_moov_size - this->m_moov_size;
				if (size_diff) {
					this->m_moov->AdjustChunkOffsets(size_diff);
				}
			}
			AP4_Result result = AP4_FileCopier::Write(*this->m_pAP4_File, *pOutputStream);
			success = AP4_SUCCEEDED(result);
			assert(AP4_SUCCEEDED(result));
			delete pOutputStream;
		}
	}
	return success;
}
```

After this the new m4a file does not show chapter markers anymore.
I'm attaching the before (with-chapters.m4a) and after (no-chapters.m4a) files here.
Thanks for your help!

[m4a-chapters.zip](https://github.com/axiomatic-systems/Bento4/files/4834144/m4a-chapters.zip)

**Comment by gmacciocca** [comment]
Also: hi, Gilles! :)

**Comment by barbibulle** [comment]
Hi Gianluca,
there was a bug that was introduced in r636 but was fixed in r637 (the latest) which I believe is what's causing the error here. The bug that was introduced failed to correctly record the sample_count field for tracks where the sample size was fixed, which is the case for track 2 here. And looking at the difference between the two files, I see that there's just one byte difference, which is exactly the sample_count field of the second track... (it is 7 in the correct file, and 0 in the incorrect one).
Can you try with the latest from the master branch to check if that works for you?

**Comment by gmacciocca** [comment]
Hi, Gilles, the latest master works!!  :) Thank you!

Now I wonder if the bug that was fixed is also the reason why I could not successfully create the text chapter-markers track with Bento4? The text chapter-markers track was created but it had none of the text (chapters) samples I had written in it. I need to re-write that code to see if it works now. Thank you again!
