### ISSUE TITLE
Using Bento4 to pack mpeg-dash with DRM protection

### ISSUE THREAD

**Issue by almoghzn** [axiomatic-systems/Bento4#54]
Hi,

1. I'm using Bento4 to create mpeg-dash that encrypted with Widevine DRM protection.
2. I'm using ExoPlayer Demo to play the mpeg-dash content (that created by Bento4).
3. I've noticed that that whole content is encrypted (Starting from the first segments).
4. I've notices that some of the samples that ExoPlayer provides are DRM protected, BUT:
the first couple of seconds (~8 seconds) of the media ARE NOT encrypted.
This used for ExoPlayer starting to play the media and requesting the decryption keys from the license provider in parallel.

I need to create mpeg-dash that is DRM protected as ExoPlayer did, i.e. the first couple of seconds will be unencrypted (to let ExoPlayer start to play the media while we're waiting for the keys response from the license provider).
Can I achieve that with Bento4 tool?

Thanks in advance for any advice.

**Comment by barbibulle** [comment]
Yes, this is supported. This is a 'hidden' feature (because it hasn't received a lot of testing), but here's how you use it:
When encrypting the content with mp4encrypt, you can set for any track the property 'ClearLeadFragments' to be an integer value indicating the number of fragments at the start of the track that should be left in the clear.

When using mp4encrypt indirectly through the mp4-dash tool, you can use the --encryption-args option to pass extra arguments to mp4encrypt. 
The slight complication here is that the property needs to be set for each track, so you'll need to know the track IDs that are part of your input (typically 1 and 2, but multi-track input can be found with larger track IDs).

Example:
(assuming movie.mp4 has two tracks, with IDs 1 and 2 respectively)
(you'll also need to add the DRM parameters for any DRM you're using, but that's independent)

mp4dash --encryption-key=000102030405060708090a0b0c0d0e0f:00112233445566778899aabbccddeeff --encryption-args="--property 1:ClearLeadFragments:10 --property 2:ClearLeadFragments:10" movie.mp4

If you run mp4dash with the '-d' option, you can observe the actual mp4encrypt command line options that are passed to the encryption tool.

Let me know if you have any issue using this.

**Comment by almoghzn** [comment]
Thank you so much for your quick answer!
It's seems to be working very well, thanks again.

Just one clarification I need:
How can I tell what is it track ID of my media file (*.mp4).
I used the mp4dash with "property 1" and it works just fine. But it was a guess.

**Comment by barbibulle** [comment]
You can find the info about the tracks in a file, include the track IDs, with the mp4info command (which can output human-readable text or JSON).
(make sure you use the ClearLeadFragments property for *all* tracks, not just track ID 1. as you can see in the example above, there's a property set for track 1 and for track 2)
