### ISSUE TITLE
Encrypt ffmpeg generated fragments possible?

### ISSUE THREAD

**Issue by hariszukanovic** [axiomatic-systems/Bento4#556]
I am using ffmpeg to generate dash fragments.
These I would like to encrypt, and I tried with mp4encrypt.. there is no error, but the output file produced is not as expected. 

* The command I use is like this:
mp4encrypt --method MPEG-CENC --key 1:a0a1a2a3a4a5a6a7a8a9aaabacadaeaf:0123456789abcdef --property 1:KID:121a0fca0f1b475b8910297fa8e0a07e chunk-stream0-00088.m4s test-enc.mp4

* output test-enc.mp4 is 9 bytes in size.
ls -l test-enc.mp4 
-rw-rw-r-- 1 haris haris 96 Oct  9 12:52 test-enc.mp4

* mp4info chunk-stream0-00088.m4s
No movie found in the file

* mp4info test-enc.mp4 
File:
  major brand:      mp42
  minor version:    0
  compatible brand: iso6
  fast start:       yes
No movie found in the file

* mp4dump test-enc.mp4 
[ftyp] size=8+12
  major_brand = mp42
  minor_version = 0
  compatible_brand = iso6
[styp] size=8+16
[sidx] size=12+40, version=1
  reference_ID = 1
  timescale = 12800
  earliest_presentation_time = 10690560
  first_offset = 0

Perhaps this should this be done with some other command?
Thank you in advance for any advice

**Comment by barbibulle** [comment]
Are you trying to encrypt just a segment by itself? If you want to do that, you need to provide `mp4encrypt` the file that contains the `moov` part of the file (what DASH calls the 'init' segment), because that's where the necessary metadata lives.
To do that, you use the `--fragments-info <filename>` option to pass the name of the file that contains the `moov`.
Also, `mp4info` isn't useful for standalone fragments, since it is a tool that looks at the metadata found in the `moov` part of a file. So you should use `mp4info` only on the  'init' segment, or a full mp4 file (if you have an init segment and media segments, you can just concatenated those together to construct a full mp4 file).

**Comment by hariszukanovic** [comment]
Thank you very much for the clarification. It works now
