### ISSUE TITLE
Track ID 1 is not a known track!

### ISSUE THREAD

**Issue by luisloros** [axiomatic-systems/Bento4#56]
Hi, after trying Bento4 to make a MPEG-DASH stream and validate it with the dash-if conformance tool, I get the following errors:
```
### error: ftyp-1
### The brand 'isom' can only be a compatible, not major, brand
'tkhd' alternateGroup must be 0 not 1
### error: sidx-1
### Track ID 1 in track reference atoms references a non-existent track
### error:
### getTrakIndexByID: Track ID 1 is not a known track!
```

Is it normal?

Commands:
`$ mp4fragment --fragment-duration 3000 --index media.mp4 fmedia.mp4`
`$ mp4dash --debug --output-dir=.\dash\ --mpd-name=media.mpd --profiles=live --use-segment-template-number-padding fmedia.mp4`

Validation tool: http://dashif.org/conformance.html

**Comment by barbibulle** [comment]
Regarding the first error ('ftyp'), the Bento4 packager does not change the major brand of the input file, it just keeps it as is and optionally adds entries in the list of 'compatible' brands. So what's going on here is that your input MP4 file isn't correct, as it uses 'isom' as a major brand. Do you know how this file was produced?

Regarding the second error: there seems to be an 'sidx' entry in your input file which is bogus. The bento4 tools don't remove bogus entries that may be in your input file. Those unknown/bogus entries will be left as-is (because the Bento4 packager doesn't know about them doesn't mean it should remove them, they may be useful for something). So, for some reason the encoder you used to create your input MP4 file has created an invalid 'sidx' for a non existent track. 

If you can share your input MP4 file, I can take a look to see how this may have happened.

**Comment by luisloros** [comment]
Yes, you were right. Adding "-movflags separate_moof+faststart" to ffmpeg encoding command solved the problem. Thank very much for pointing it out!

FFMPEG encoding command:
`ffmpeg.exe -i input.mp4 -c:a -vf scale=1280:720 libvo_aacenc -ab 128k -ac 2 -c:v libx264 -x264-params b-adapt=0:bframes=3:ref=3:keyint=75:fps=25:bitrate=5000:vbv-maxrate=5000:vbv-bufsize=5000:scenecut=0:min-keyint=75 `**`-movflags separate_moof+faststart`**` media.mp4`
