### ISSUE TITLE
Encryption and decryption failure on FFmpeg-generated fMP4 segments

### ISSUE THREAD

**Issue by dustsigns** [axiomatic-systems/Bento4#578]
Good day,

I try to encrypt and decrypt a segment file (MP4 fragment) which has been generated by FFmpeg. Bento4 seems to provide multiple ways to do this, but all of them either fail with relatively unspecific error messages or end up just copying the file.

Input file(s)
===

I use a 25-fps file with one audio track and one video track (I tried multiple different ones). I encode the file using FFmpeg like this:

    ffmpeg -i input.mp4 -acodec aac -vcodec h264_nvenc -b:v 2500k -g 5 -rc cbr_ld_hq -hls_segment_type fmp4 -hls_time 2 -hls_segment_filename stream-%%18d.m4s -hls_fmp4_init_filename init.mp4 -hls_playlist_type vod -t 10 index.m3u8

This generates a playlist (index.m3u8), an initialization segment (init.mp4) and five segments (stream-000000000000000000.m4s to stream-000000000000000004.m4s). For testing, I only use the initialization segment (init.mp4) and the first segment (stream-000000000000000000.m4s). They are placed in a folder called orig. I uploaded them as [segment.zip](https://github.com/axiomatic-systems/Bento4/files/5943732/segment.zip) here for reproducibility.

Encryption attempts
===

I tried to encrypt the first segment using the three different ways offered by Bento4 - mp4-hls, mp4-dash as well as mp4encrypt directly.

mp4-hls
---

    .\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\utils\mp4-hls.py --exec-dir=.\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin --encryption-key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb -o enc\ orig\stream-000000000000000000.m4s

This call fails with the following output:
```
Parsing media file orig\stream-000000000000000000.m4s
ERROR: 'tracks'
```
It seems that mp4-hls does not support fragmented MP4 files (that's reasonable since there is no parameter to pass the initialization segment). A more specific error message would, however, be nice.

mp4-dash
---

    .\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\utils\mp4-dash.py --exec-dir=.\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin --encryption-key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --encryption-cenc-scheme=cbcs --init-segment=orig\init.mp4 --hls -o enc\ orig\stream-000000000000000000.m4s

This call fails and prints "ERROR: 'tracks'". As this was not very descriptive, I investigated it in a debugger and found that mp4info seems to be unable to find any tracks. I do not understand why. However, a more detailed error message would, again, be nice.

mp4encrypt
---

I tried encryption with two different methods:

    .\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\mp4encrypt.exe --method MPEG-CENC --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbb --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbb --fragments-info orig\init.mp4 orig\stream-000000000000000000.m4s enc\stream-000000000000000000.m4s

    .\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\mp4encrypt.exe --method MPEG-CBCS --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --fragments-info orig\init.mp4 orig\stream-000000000000000000.m4s enc\stream-000000000000000000.m4s

Both calls seem to generate an encrypted fragment named stream-000000000000000000.m4s in the folder enc, but I cannot get them decrypted (see below).

Decryption attempts
===

I tried to decrypt the encrypted segment (that I generated with mp4encrypt) in two different ways - with mp4decrypt and with a specifically designed playlist to be used with FFplay.

mp4decrypt
---

    .\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\mp4decrypt.exe --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --fragments-info orig\init.mp4 enc\stream-000000000000000000.m4s dec\stream-000000000000000000.m4s

This call seems to succeed, but the output segment is bit-identical to the input file. mp4decrypt seems to just copy the file and there is no error message.

FFplay
---

To play back the encrypted segment (forcing decryption in the process), I copy the initialization segment (init.mp4) and the encrypted segment into a new folder, add a key.bin file with 16 bytes of "aa" (hex) and design a playlist (index.m3u8) file like the following:

```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="init.mp4"
#EXT-X-KEY:METHOD=AES-128,URI="key.bin",IV=0xBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
#EXTINF:2.000000,
stream-000000000000000000.m4s
#EXT-X-ENDLIST
```

*Note: I adjust the IV depending on the method, see above*.

Attempting to play back the playlist with

    ffplay -allowed_extensions ALL .\index.m3u8

results in FFplay not recognizing the file properly:

    Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1920x1080): unspecified pixel format

Question
===

How can I use Bento4 to encrypt and decrypt an FFmpeg-generated fMP4 segment? Decryption can be done by either Bento4 or FFplay. I explained my attempts above - if I have made a mistake somewhere, please let me know and maybe use it as input for some more detailed error messages, where applicable. Thank you.

**Comment by barbibulle** [comment]
Hi.
There are several points to address here. Overall, what you're trying to do is definitely supported by Bento4. Let's address the points one by one:

First, it seems you're using ffmpeg in a mode where it is producing an HLS presentation, with discrete init segment, media segments, and manifest, rather than a single MP4 file. That's perfectly fine, and in this case you'll need to encrypt the segments one by one yourself, as well as 'patch' the manifest. If all you want is the encrypted HLS presentation, you could, instead, use `mp4dash` (or `mp4hls`, but that doesn't support fragmented MP4 segments, only TS segments, you need to use `mp4dash` for that) , but you'd need to use ffmpeg in a more standard mode, where it outputs an MP4 file, not an HLS presentation.
This is why you're seeing an error with `mp4dash` and `mp4hls`, as those programs work on full MP4 file, not individual segments.
NOTE: you can also easily go from individual init and media segments to a single file by just concatenating the init segment and the media segments.

Second, about the encryption of the individual segments, if that's the option you prefer, with `mp4encrypt` (which is perfectly fine, in fact, that's what `mp4dash` uses internally to automate the encryption of the segments automatically for you): the init segment is important, because even though it doesn't include any media samples, it contains the information about the tracks, and for an encrypted presentation, there's crypto information in there.
So you need to encrypt the media segments, as you're doing in your examples, but also the init segment. And when decrypting the segments one by one, you need to point to the 'encrypted' init segment for info.
So here, your `mp4encrypt` commands look fine, but you also need something like:
```
mp4encrypt --method MPEG-CENC --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbb --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbb init.mp4 enc-init.mp4
```

And when when decrypting:
```
mp4decrypt --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa enc-init.mp4 dec-init.mp4
```
for the init segment, and something like
```
mp4decrypt --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa --fragments-info enc-init.mp4 enc-000.m4s dec-000.m4s
```
for the media segments

Finally, the error you're seeing when attempting to play the encrypted HLS presentation is due to the fact that you're still pointing to the non-encrypted `init.mp4`.

**Comment by dustsigns** [comment]
Hi,

Thank you very much for your help. Using `mp4encrypt` on the init.mp4 as well, I managed to get a file which I could decrypt again in a bit-identical way. However, FFmpeg still gives me the same error message on the encrypted init.mp4 and the encrypted first segment:

```
[hls @ 000002c874d61680] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1920x1080): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

I tried both, CENC and CBCS, although I think CBCS is the mode that I should use here. The commands I used (for CBCS) were:

```
.\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\mp4encrypt.exe --method MPEG-CBCS --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb orig\init.mp4 enc\init.mp4
.\Bento4-SDK-1-6-0-637.x86_64-microsoft-win32\bin\mp4encrypt.exe --method MPEG-CBCS --key 1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --key 2:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --fragments-info orig\init.mp4 orig\stream-000000000000000000.m4s enc\stream-000000000000000000.m4s
```

The playlist is the same as in my post above. I would be very thankful for any pointers on how to make the encrypted file play.

Regarding Bento4, is there a way to let the user know that `mp4-hls` explicitly requires unfragmented MP4 files, and would there be a chance that `mp4-dash` encrypts the init.mp4 segment in addition when one is provided so that the manual calls to `mp4encrypt` can be automated?

**Comment by dustsigns** [comment]
Hi,

Are there any updates or hints on this? The Bento4-created CBC1-encrypted file(s) cannot be played back or processed with (the latest version of) FFmpeg or FFplay, despite the key being correct. I would be thankful for any pointers.

**Comment by barbibulle** [comment]
Hi. If you want to use mp4 fragments with HLS, you'll need to use CBCS (`METHOD=SAMPLE-AES` in the HLS playlist). See https://tools.ietf.org/html/rfc8216 
If you specify `METHOD=AES-128` in your HLS playlist, this tells the player/decrypter that the segments are bulk-encrypted, not encrypted on a per-sample basis. You can use `METHOD=AES-128` with HLS when using media segments in MPEG2TS format, not MP4 (the `mp4hls` tool can generate such a format for you if that's what you want).

Also, I'm not sure what you mean by "_would there be a chance that mp4-dash encrypts the init.mp4 segment in addition when one is provided so that the manual calls to mp4encrypt can be automated_". When you use `mp4dash` to encrypt your content, you typically give it a key and it will encrypt all the segments for you, including the proper signaling in `init.mp4`. You can use it in a mode where you give it pre-encrypted content, in which case it won't encrypt anything, it will just generate the manifest (that's only useful for advanced use cases where for some reason you want/need to encrypt the content separately ahead of time without generating the manifest at that time).

**Comment by dustsigns** [comment]
Thank you very much for the hint. I fixed my commands to use CBCS and change the METHOD to SAMPLE-AES in my playlist. Unfortunately, FFmpeg does not support this type of encryption. Can you recommend any player which supports it so that I can test whether my playlist and the encrypted segments are correct and can be played back (decrypted)?

Regarding mp4dash, I do indeed have the situation where I want to first encrypt the content and then compile a playlist later. If I understood correctly, I should use mp4encrypt. That's perfectly fine for me.

**Comment by barbibulle** [comment]
If you want to test an HLS playlist with SAMPLE-AES, you can use a mac or iPhone, that usually works well. Another player option is a web-based player, like https://shaka-player-demo.appspot.com/demo 

For the use case of using mp4encrypt first and then mp4dash, while this is an advanced scenario, it is possible. You'll need to ensure that you've set up all the metadata correctly (Key IDs, etc.) at encryption time. The best way to get more familiar with that is to look at how `mp4dash` uses `mp4encrypt` internally when you tell it to encrypt the content.
