### ISSUE TITLE
HOWTO: Have audio tracks for Castilian Spanish and Mexican Spanish

### ISSUE THREAD

**Issue by mich-winkel** [axiomatic-systems/Bento4#58]
Hello,
We need to be able to provide Castilian and Mexican Spanish audio for our content.  It does not appear that the ISO 639-1 or 639-2 codes provide the ability to distinguish between these two languages.  I tested using 2 audio files (one es-ES and one es-MX) found that there was only 1 folder called spa in the audio folder.   
Is there a way that I can tag the audio tracks or change how the audio files are written out so that we can provide both languages?

We are using Bento4 mp4-dash to create the mpeg-dash for Widevine, Cenc, Playready and Marlin.

Thank you very much for your assistance.
Michelle Winkel

**Comment by barbibulle** [comment]
There's actually an command line syntax to enable you to do what you want here:
When you specify the inputs to mp4-dash, you can use a selector/filter in front of any of the filename. That can be used to select a specific track by ID or type, and also to override or set some parameters, like the language code.
Since es-ES and es-MX are not going to be signaled in your MP4 input, I assume here that your input has two tracks with simply 'spa' as the language code (or you have one audio-only MP4 file for each of your languages). What you'll need to do is use the input selector syntax like this:
let's say you have your input file media.mp4, with track 1 = video, track 2 = audio with es-ES, and track 3 = audio with es-MX
you would use a command line like:
mp4-dash [track=1]media.mp4 [track=2,+language=es-ES]media.mp4 [track=3,+language=es-ES]media.mp4

In an input selector, the param=value syntax represents a filter, and +param=value represents an override, so something like [track=2,+language=es-ES] means: use only track ID = 2 from the file, and override the language to be es-ES.

**Comment by mich-winkel** [comment]
Hi, thank you for your quick response.

We are sending in language=es-ES and language-es-MX.  Below is the parameters I am passing into the call to mp4-dashh.py :

--marlin --primetime --encryption-key=18E01791A8BEC3989FDBA81AE4372787:CF146079552617496484B81467F6B560 --mpd-name=A00928_E2_WS_XX_XX.mpd --widevine --widevine-header=provider:swank#content_id:3138453031373931413842454333393839464442413831414534333732373837 --playready --playready-header=LA_URL:http://test.prmmixdrm.com/RightsManager.asmx -o E:\output\cenc\A00928_E2_WS_XX_XX\47410649 -f [type=audio,language=en-US]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_en-US.mp4 [type=audio,language=de-DE]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_de-DE.mp4 [type=audio,language=es-ES]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_es-ES.mp4 [type=audio,language=es-MX]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_es-MX.mp4 [type=audio,language=it-IT]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_it-IT.mp4  [type=video]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_480p_800kbps_en-US.mp4 [type=video]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_720p_1200kbps_en-US.mp4 [type=video]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_480p_1500kbps_en-US.mp4 [type=video]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_720p_2000kbps_en-US.mp4 [type=video]E:\output\cenc\A00928_E2_WS_XX_XX\47410649\fragmented\A00928_E2_WS_XX_XX_720p_3000kbps_en-US.mp4

**Comment by barbibulle** [comment]
If you want to override the language value, you need to use the '+' sign in front of the language parameter in the input selector. For example, use [type=audio,+language=en-US] instead of [type=audio,language=en-US]

**Comment by mich-winkel** [comment]
Thank you so much.  That was exactly what I needed.
