### ISSUE TITLE
HOWTO: Is it possible to force the order of the Audio tracks in the MPD to be something other than the default?

### ISSUE THREAD

**Issue by mich-winkel** [axiomatic-systems/Bento4#59]
I have the need to have the first audio track to be the language the film is produced in (theatrical language).  Even though I pass the track in the order I would like them to be in the MPD, it appears that the are written in a different order (alphabetical ?).  

Is there a way to force the order or is there another way to indicate which audio file is the theatrical language?  I tried adding +role=main (e.g. [type=audio,+language=English,+role=main] ) but that did not seem to affect the resulting MPD file.

Thank you,
Michelle Winkel

**Comment by barbibulle** [comment]
I could add an option to list tracks in the order they were found in the input sources (command line), but that shouldn't make a difference, as the order in the XML MPD isn't supposed to be significant. I think I'll add that option anyway, because I suspect some players will default to that.

Regarding the specification of the 'role' attribute, even though this appears in the code in some places, that's not an implemented feature yet (I started looking at it, but haven't finished). I intend to fully support multi-role and multi-adaptation-set features very soon.
Also, if you want to override the language with '+language=', you need to specify the language in the format required by the DASH spec (IETF RFC 5646). So 'English' won't work, you would need '+language=en'

Also, what do yo mean by 'theatrical'? The roles defined in the base DASH spec include:
main, alternate, commentary, supplementary, dub, and a few more.

**Comment by mich-winkel** [comment]
Thank you for your quick response.

I apologize for my mistake with the language; I meant to type en-US instead of English.

A theatrical language is the language the movie was primarily filmed in.  For example, the theatrical language for the movie Motorcycle Diaries has Spanish as the primary language and so its theatrical language is Spanish.  
I would use +role=main for the theatrical language and +role=alternate for the other audio languages.

Should I add a formal request for the ordering of the audio files and implementation of the role attribute?

Thank you,
Michelle
