### ISSUE TITLE
mp4decrypt check key is correct

### ISSUE THREAD

**Issue by AlexHighTower** [axiomatic-systems/Bento4#612]
Hello,

Is is possible to check if used key for decryption is correct key?
Because now if key is correct mp4decrypt generates output and have exit code 0
mp4info not show that output file in this case if encrypted, but in fact output file is garbage...

any possibility?

**Comment by barbibulle** [comment]
Unfortunately the MP4 encryption/decryption spec does not include a verification code/checksum, so the only way to check if a decryption key is correct is to check that the decrypted content is correct. It may be possible to use some quick check (decrypt a few bytes only and try to detect if they look like valid encoded media, according to the codec specification), but that is very codec-specific, and not fool-proof. If you always work with the same codec types, the task may be simpler, because you wouldn't need to know how to detect very codec syntax. For H.264 and H.265, the Bento4 SDK does contain codec parsers, so these could be used to try and parse decrypted video frames to check whether they look correct or not. This should be fairly easy for AAC audio elementary streams as well.
