### ISSUE TITLE
How to reduce video file size in Bento4?

### ISSUE THREAD

**Issue by adrianbartyczak** [axiomatic-systems/Bento4#714]
I'm using Bento4 in an Android app to split videos from my camera, and it's working fine. However, they are not compressed, so the video segments are larger than I want them to be. For example, a 6 second clip is about 38MB (using MPEG2-TS).

I'm not a C++ coder, so I don't know how to change the bitrate or video resolution in Bento4. Can someone help me?

The respective files I'm using are:

[/Source/C++/Apps/Mp4Split/TransportStream.cpp](https://www.dropbox.com/s/v18l19zyfld23vi/TransportStream.cpp?dl=0)

[/Source/C++/Core/Ap4Mpeg2Ts.cpp](https://www.dropbox.com/s/fmmbvuy0x9xqjc3/Ap4Mpeg2Ts.cpp?dl=0)

[/Source/C++/Core/Ap4Mpeg2Ts.h](https://www.dropbox.com/s/swz13z2wr8o6pkt/Ap4Mpeg2Ts.h?dl=0)

Thanks

**Comment by barbibulle** [comment]
Hi.
Unfortunately, changing the resolution of an encoded stream isn't something you can simply do like this. Once encoded, the resolution (and thus also its size, bitrate, etc.) is fixed, so you'd have to re-encode them if you wanted to change that. If I understand your use case, it seems that you should be able to configure your media source so that it would give you compressed video instead of uncompressed, and select a resolution and bitrate that meet your size requirements.
