### ISSUE TITLE
Example showing how to use Bento to apply a distinct encryption key for each track

### ISSUE THREAD

**Issue by kidmiracleman** [axiomatic-systems/Bento4#73]
Hi,

As per the title  - I am trying to figure out (via docs / code scanning), how to apply DRM to a DASH stream and use different encryption keys for audio and video tracks.

Is there a known example showing the args that need to passed to mp4-dash.py that will allow me to achieve this?

Thanks in advance

**Comment by barbibulle** [comment]
There's experimental support for specifying different keys for audio and video. But please bear in mind that not all DRMs will allow you to create licenses with different keys for audio and video, so make sure that the DRM you're using can actually do that.
Alternatively, you can choose to encrypt the video and leave the audio in the clear (or vice-versa)
The way you do this with mp4dash is by using track filters in the --encryption-key option, and using one or more entries (separated by ',').
Example:
mp4dash --encryption-key=audio:000102030405060708090a0b0c0d0e0f:00112233445566778899aabbccddeeff,video:a0a1a2a3a4a5a6a7a8a9aaabacadaeaf:b0b1b2b3b4b5b6b7b8b9babbbcbdbebf input.mp4

Let me know if this works for you.

**Comment by araipiyo** [comment]
Hi, 

Is there any way to use different encryption keys for different representations, such as HD quality and SD quality video? I'm trying to figure out how to make different pricing for different quality, while maintaining HD quality playback is possible to fall back to SD quality.

Regards,

**Comment by barbibulle** [comment]
This would be technically possible, but not supported at this point. It is also risky to get to that level of granularity, as some players will definitely not support it (they don't want to or can't switch decryption keys seamlessly as they switch bitrates), so I would recommend avoiding it.

**Comment by araipiyo** [comment]
Thank you for reply. I really appreciate. I must figure out some other way to make that possible.

**Comment by barbibulle** [comment]
It is possible to do it, with a bit of manual work: you can encrypt the
input MP4 files directly with mp4encrypt before passing them to mp4dash.
mp4dash should be able to work with pre-encrypted input. The only issue I
can foresee here is that as a result, different representations will end up
with different KIDs, which might confuse the mp4dash packager. I have not
tried this scenario, but it is work trying out.

**Comment by araipiyo** [comment]
Thanks, how about if I create a two set of DASH files for HD stream and SD stream by mp4dash and combine two mpd files to one manually? However, I'm not really sure how can I put two KIDs into mpd file.

If it doesn't work, probably we will take a safer way and provide two different streams for HD and SD versions, and either we make let users to manually switch between streams, or we encrypt SD versions with two different keys.

**Comment by barbibulle** [comment]
You can definitely combine two MPDs manually. If the content protection settings are different for different representations, then you'll have to put the <ContentProtection> element at the representation level instead of the adaptation set level (which is what's done currently).
In any case, you'll have to create two MPDs: one for clients who are not allowed to get the HD representations (because if you give them an MPD with representations that they can't play, that will break their player, since they won't know they're not supposed to play those, and will get a DRM error when they try), and one for the clients who can access both SD and HD. For the SD+HD case, the client will need to acquire two licenses (most DRMs only support returning one key per license, so if you have two keys, you'll need two licenses), which can be a burden on your DRM infrastructure. Something to keep in mind.

**Comment by araipiyo** [comment]
Thanks! I will give it a try, and I will back to you with device testing result.
