### ISSUE TITLE
mp4-dash atmos error

### ISSUE THREAD

**Issue by riba101** [axiomatic-systems/Bento4#730]
Hi all,

I'm running into a issue with MP4's with Dolby Atmos

When I run  these commands,

`mp4fragment './media/Universe_Fury2.mp4' './media/Universe_Fury2.mp4-f.mp4'`
`mp4-dash.py './media/Universe_Fury2-f.mp4' --hls --profile='on-demand' -o'./packaged/'`

I get the following console log error.

```
ERROR: 'atmos'

Parsing media file 1: ./media/Universe_Fury2-f.mp4
Extracting track 2 from ./media/Universe_Fury2-f.mp4
Extracting track 1 from ./media/Universe_Fury2-f.mp4
Parsing media file 1: tmp7d7rnngy = Extracted[track 2 from ./media/Universe_Fury2-f.mp4mp4]
Parsing media file 2: tmppclu11qi = Extracted[track 1 from ./media/Universe_Fury2-f.mp4.mp4]
Processing and Copying media file tmp7d7rnngy = Extracted[track 2 from ./media/Universe_Fury2-f.mp4.mp4]
Processing and Copying media file tmppclu11qi = Extracted[track 1 from ./media/Universe_Fury2-f.mp4]
[Finished in 5.5s with exit code 1]
```

The media used for this is a demo mp4 from Dolby tah can be found here https://developer.dolby.com/tools-media/sample-media/video-streams/hd-video-streams/

Running the code from the latest code from github (cloned 25 July 2022)

**Comment by Radoslaw-Adamowski** [comment]
This is an issue of using wrong key when checking if atmos is present in audio track 

The source of the issue is in file Bento4/Source/Python/utils/mp4utils.py
```
Traceback (most recent call last):
    File "./mp4-dash.py", line 2233, in <module>
     main()
    File "./mp4-dash.py", line 2211, in main
     OutputDash(options, set_attributes, audio_sets, video_sets, subtitles_sets, subtitles_files)
    File "./mp4-dash.py", line 506, in OutputDash
     audio_sets = ReGroupEC3Sets(audio_sets)
    File "/home/R.Adamowski/Workspace/repos/Bento4/Source/Python/utils/mp4utils.py", line 981, in ReGroupEC3Sets
     if track.info['sample_descriptions'][0]['dolby_digital_plus_info']['atmos'] == 'Yes':
KeyError: 'atmos'`
```
Now the structure contains 'Dolby_Atmos'  instead of 'atmos'.

`{'dec3_payload': '1400200f000108', 'data_rate': 640, 'Dolby_Atmos': 'Yes', 'complexity_index': 8, 'substreams': [{'fscod': 0, 'bsid': 16, 'bsmod': 0, 'acmod': 7, 'lfeon': 1, 'num_dep_sub': 0, 'chan_loc': 0}`

For easy workaround just change it in the py file.
