### ISSUE TITLE
Failing to correctly do AP4_CencSampleInfoTable::Create on particular file

### ISSUE THREAD

**Issue by glennguy** [axiomatic-systems/Bento4#781]
Hi again
The attached zip contains the init and a segment from an audio track of a CBCS encrypted stream:
[audio.zip](https://github.com/axiomatic-systems/Bento4/files/9674419/audio.zip)
This decrypts successfully in browser/official app, but bento4/Kodi/inputstream.adaptive is not currently handling this properly.

When trying to create a sampleinfotable it's missing data because there's no SAIZ/SAIO boxes, and the SENC box is effectively empty:
![image](https://user-images.githubusercontent.com/11909320/193027266-6ad86e89-bde1-411b-8882-682d89695af6.png)

This here actually creates the sampleinfotable: https://github.com/axiomatic-systems/Bento4/blob/5b7cc2500d514717a64675fcf631939494c074ce/Source/C%2B%2B/Core/Ap4CommonEncryption.cpp#L2828-L2838
But m_sampleCount is 0 (and probably more data missing too), no IVs are stored and ultimately calling DecryptSampleData fails here: https://github.com/axiomatic-systems/Bento4/blob/5b7cc2500d514717a64675fcf631939494c074ce/Source/C%2B%2B/Core/Ap4CommonEncryption.cpp#L2127

I'm hoping you can help with a solution or at least point me in the right direction. I've been at it for a couple of hours and tried a few things but now getting to the point of needing some help.

Thanks heaps.

edit: btw this is from the same stream/program with incorrect boxes in the video stream from issue #742

**Comment by glennguy** [comment]
Hi I have some more info.

So I now see that the 'data' in this box is indicating that there's a 0 count for sample info.

From this document: https://www.uvcentral.com/files/CFFMediaFormat-2_1.pdf on page 39
> sample_count is the number of encrypted samples in this track fragment. This value SHALL be
either zero (‘0’) or the total number of samples in the track fragment.

I have a workaround here but not really sure if it's proper. I just copy/pasted code from another function that gets the sample info count from the trun box. With this number populated the table is successfully created. I also had to alter `SetSampleInfoSize` to update `m_SampleInfoCount` - this made sense to me: https://github.com/glennguy/Bento4-axiomatic/commit/5b5200b01a243fe4be7fd72559ac356ef3cc0cad

Grateful for your feedback.

**Comment by barbibulle** [comment]
This file is also not compliant (no `saiz` and `saio`, which are required by the spec). 
I committed a change to the main branch that supports this case where `saiz` and `saio` are missing, and an `senc` box is present with `sample_count == 0`. In this case, all samples will use the same default IV.
Note that this is implemented with a special case for `sample_count == 0` rather than building a table for all the samples, because just looking at the sample count in a `trun` box isn't enough to know how many samples there may be.
I couldn't verify that this works for your file, other than it not erroring out, because I don't have the decryption key, so I can't check that the decryption was actually correct. 
Please let me know if this fix works for you.

**Comment by glennguy** [comment]
Thanks for looking at this @barbibulle 
Works like a charm, thanks heaps for very fast turnaround!
