### ISSUE TITLE
Is Bento lib reentrant/threadsafe?

### ISSUE THREAD

**Issue by hariszukanovic** [axiomatic-systems/Bento4#783]
To add some context to the question:
Using master branch...
My code is more or less the same as in mp4encrypt app main function. I have linked the library into my multi-threaded application that can execute many threads simultaneously. If I execute only 1 thread, everything seems to works just fine. If I execute many threads I get the assertion below... (always reproducible after running for a short while)

Bento4/Source/C++/Core/Ap4Atom.cpp:763: virtual AP4_Result AP4_AtomListWriter::Action(AP4_Atom*) const: Assertion `bytes_written <= atom->GetSize()' failed.

**Comment by barbibulle** [comment]
The library is designed to be safe for this type of multi-threaded use. As long as you don't share mutable objects between threads, you should be able to have multiple threads create and use their own objects without interfering with each other.
There is one case where you'll need to be explicit about not using a shared object:
For backward-compatibility reasons, the AP4_Processor::Process method takes an instance of AP4_AtomFactory as a parameter, but it has a default parameter value that uses a shared instance. So if multiple threads invoke AP4_Processor::Process() at the same time, there can be a race condition if the state of that shared object is mutated by a thread while used by another thread.
Fortunately, it is easy to avoid that problem, all you have to do is pass a non-shared instance of AP4_AtomFactory when calling AP4_Processor::Process(). You can create that object locally just before calling the method (you can allocate it on the stack, it doesn't need to last after the method returns).
Example:
instead of
processor->Process(input, output);
which will use the default arguments, use something like:

AP4_AtomFactory atom_factory;
processor->Process(input, output, NULL, atom_factory);
