### ISSUE TITLE
mp4dash: Definition of required bandwidth

### ISSUE THREAD

**Issue by rodrigobdz** [axiomatic-systems/Bento4#88]
Enabling verbose and debug mode in mp4dash prints out average segment bitrate, max segment bitrate and required bandwidth for each video representation.
This **required bandwidth** equals bandwidth under each representation in the manifest created by mp4dash.

**How is this value calculated?** 
This should be documented.

Thanks in advance.

**Comment by barbibulle** [comment]
The required bandwidth calculation is somewhat complicated. What this value represents is the bandwidth value for which, if the throughput remains constant as that value there should never be an underflow situation. The client is only required to buffer @minBufferTime worth of data. In theory, a precise calculation for this would require looking at every frame, and taking the possible frame reordering into account. But the current method isn't quite that complicated. It looks at the minBufferTime value and the individual segment sizes, and finds a value for which the client buffer would never go empty. This is better than just taking the average segment bitrate (which would be wrong, since there are often peaks), but not quite as precise as looking at individual frames.
