### ISSUE TITLE
mp4mux ERROR: unsupported input type 'C'

### ISSUE THREAD

**Issue by grundysf** [axiomatic-systems/Bento4#963]
Is mp4mux not able to accept absolute paths for input files on Windows machines?  Having trouble when using absolute paths, always receiving error: ERROR: unsupported input type 'C'

Have tried quotes around paths with no success. Using relative paths is ok and works just fine?

**Comment by barbibulle** [comment]
Unfortunately, `mp4mux` uses the `:` character as a delimiter when specifying the input file type explicitly (instead of guessing from the file extension). That's an oversight... But you should be able to use windows absolute file paths by specifying the file type explicitly.
For example: `mp4mux --track h264:c:\my_video.h264 --track aac:c:\my_audio.aac muxed.mp4`.

**Comment by grundysf** [comment]
specifying the file type explicitly works perfectly. Thank you
