### ISSUE TITLE
ERROR while writing atoms to output file

### ISSUE THREAD

**Issue by nguyevt** [axiomatic-systems/Bento4#97]
While running the following command:

mp4Tag --add "foo.baz.bar/encoder:S:123" ${HOME}/Desktop/input.m4a ${HOME}/Desktop/output.m4a

I ran into some issues while trying to write the new atom to the output file. I got the following ERROR:

ERROR: atom size mismatch (declared size=19, actual size=272)
       while writing [data]
       while writing [----]
       while writing [ilst]
       while writing [meta]
       while writing [udta]
       while writing [moov]
Assertion failed: (after-before == atom_size), function Write, file /Users/nguyevt/workplace/Gapless/Bento4/Source/C++/Core/Ap4Atom.cpp, line 249.

Am I running the command incorrectly? Or is there a bug when trying to set my own custom atoms?

**Comment by barbibulle** [comment]
This type of exception happens when an atom is serialized and that the number of bytes written (as a result of calling the atom's Write() method) doesn't match the declared size of the atom. It could happen if the original MP4 file is somehow invalid (with mis-declared atom sizes) but not badly enough to prevent the parser from parsing it. It would also be caused by some bug in one of the atom classes' serialization method. Here, from the trace, it looks like there's a 'data' atom that ended up writing 272 bytes out when in fact it should have been 19. 
Since I'm able to reproduce this exact error on my test files, it doesn't look like it is an issue with a bogus file, so I will have to look into this and let you know what I find out.

**Comment by barbibulle** [comment]
Ok, found the bug. I committed a fix for it. Only 3 characters changed ;-)

**Comment by nguyevt** [comment]
Fix is confirmed, thanks!
